name = "MyExample"
uuid = "6cbd4f4a-0855-45d4-8521-1cf134f16623"
authors = ["m-arifin"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
